### ISSUE TITLE
Migrate docs to roxygen2

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/smatr#11]
Arises from #8

Is it possible to migrate without rewriting?

**Comment by fontikar** [comment]
Holy moly, I did a function by hand but then I found this: https://yihui.org/rd2roxygen/ pretty empty github but amazing, it seems to work! Just need to tweak now!

**Comment by dfalster** [comment]
Excellent!

**Comment by fontikar** [comment]
Needs lots of tweaking because roxygen has moved on from a lot of the \item sort of notation!

**Comment by fontikar** [comment]
Using this: https://github.com/wviechtb/mathjaxr to write math equations in the help files! Tricky to use and a bit buggy

**Comment by fontikar** [comment]
This is a bigger problem that I imagined. Mathjaxr with is an add-on for documentation DOES NOT play well with using markdown capabilities (https://roxygen2.r-lib.org/articles/markdown.html) 

It is one or the other. Given that the amount of math equations in the documentation is pretty trivial e.g.
`The common slope (\mjseqn{\hat{b}}) is estimated from a maximum of 100
iterations, convergence is reached when the change in \mjseqn{\hat{b} < 10^{-6}}`

I'm inclined to ditch mathjaxr because the handiness of markdown language is really helpful for the long documentation for sma.R

**Comment by fontikar** [comment]
- [x] OK my plan of attack is to create a branch from 2ef8723 called `documentation` and remove all mathjaxr code and simplify the math equations. At the moment the tests branch has too many features (fixing measurement error V2 with David #6 and migrating to roxygen #11) and its getting a bit disorganised and holding up progress!

Will touch base here on how to simplify the math equation from memory it was very minor and definitely do-able!  

- [x] I will also rename `tests` branch to `measure_error ` so it describes what I am working on better! 

- [x] I will delete `develop` it was redundant to tests, originally it was for fixing other issues but the roxygen documentation was creating problems on that branch. 

- [x] Finally, I feel like some of the changes (from f3fe6d6 ) I made on `master` that pertains to #6 should just be confined to the `measure_error` branch as its breaking vignette building, perhaps we can roll back to an early commit where all the problems are there but functional that way I can merge each feature release back to master knowing things won't break (e.g. some on the `summary` branch deals with #4 and #7 are ready to go!) 

Let me know if this is okay with you @dfalster just a major clean up!

**Comment by fontikar** [comment]
I am going to pick this back up now, now that all the issues that pertain to code are fixed! 
Working on a branch `documentation` and will do a mass migrate to roxygen and then we will rebuild pkgdown as some functions are missing and causing the GHA to fail!
